# version: '3.8'

services:
  postgres:
    image: postgres
    container_name: blog-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d blog"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: blog-server
    restart: always
    environment:
      DB_URL: postgres://admin:admin@postgres:5432/blog
    ports:
      - "8080:8080"
    volumes:
      - server_data:/usr/local/bin
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blog-frontend
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - server

volumes:
  postgres_data:
  server_data:
